version: '3'
services:
  label-studio:
    container_name: ${CONTAINER_PREFIX}
    build:
      context: ..
      dockerfile: docker/label-studio/Dockerfile
      args:
        DATASCIENCE_UID: ${HOST_UID}
        DATASCIENCE_GID: ${HOST_GID}
        DATASCIENCE_HOME: ${PROJECT_DIR}
    environment:
      - "APP_PORT=${APP_PORT}"
    volumes:
      - ${PROJECT_DIR}/annotation_app:/label-studio/data
    ports:
      - ${APP_PORT}:8080
